Close #5: Create a component of the first task of the first practicum (#13)
Implement `first/FirstA` component for the first task of the first practicum.

- Use `ncu` shortcut for `npm-check-updates`
- Install `webpack-cli` to run development server
- Install `@babel/plugin-proposal-class-properties` plugin.
  Source of the solution for
  `Cannot find module '@babel/plugin-proposal-class-properties'`
  https://github.com/babel/babel/issues/8655#issuecomment-476235384
- Move `babel` configuration to `package.json`
- Fix `eslint` `Parsing error: Unexpected token =` for static field.
  The solution is https://stackoverflow.com/a/44626825/1305036
- Use `Component` instead of `React.Component`